### ISSUE TITLE
[Bug]: Mobile Editor

### ISSUE THREAD

**Issue by nr458h** [TheodoreChu/append-editor#113]
**Describe the bug**
I am not sure this is a bug or not supported at the moment. When I open a note created with the Append-Editor on the smartphone I get the following error

> This extension is not installed correctly. Please use the web or des...
Re-Install Extension

**To Reproduce**
1. Create a note at the desktop with the append-editor
2. Go to the same note at the smartphone
3. Open the app

**Expected behavior**
Use the append editor for the same note

**Desktop (please complete the following information):**
 - OS: Android

**Comment by TheodoreChu** [comment]
Hi @nr458h,
Thanks for bringing this up. I'm sorry to hear that the editor is not working on Android. To help troubleshoot this issue, can you log into the Web app on your computer, open a note with the Append Editor, click the **?** on top (help button), scroll down, click "**Need more help?**", and let me know which version you are using? I'm aware that `v1.2.4` had issues on mobile, but these should have been fixed with `v1.2.5`.

**Comment by nr458h** [comment]
Hey @TheodoreChu 
Thanks for the quick reply.
In the desktop App it says 1.2.5

I already toggeld "use hosted when local is unavailable" off and on again

**Comment by TheodoreChu** [comment]
I see, thanks. Can you try the `v1.2.6-alpha.1` to see if it works? Here is the installation link for Alpha: https://notes.theochu.com/p/wVH1OyOI0Y

**Comment by nr458h** [comment]
Thanks again for the quick reply. 1.2.6 seems to work (I can open notes and edit them but I didn't looked into it more detailed)

**Comment by TheodoreChu** [comment]
Great. Please let me know if you have any more issues.

**Comment by nr458h** [comment]
Thanks at the moment no problems ;)
